# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 936b8dc5428a02af8de9b466c9289ffcb74ebc508bbd1818d4aafffb6fca4f60d777940c957e04d18f5cf7d67d5394e2837023a4e8aae5f7fbd9fa4d4d021250

test:
  secret_key_base: 2b1997abcda243f543a7717eb5b927f1d3af222a4592300f421a3e79a4a8cf5f13c4ebdb1960d09c741c4fbf8932450774102767adf3f4db49d21792c16624fd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
